# Generated by Django 3.2.9 on 2021-12-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
